version: '3.6'
services:
  web:
    build: .
    volumes:
      - ./src:/app
    ports:
      - 11337:1337
    networks:
      - private
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - database
    links:
      - database:database
    environment:
      - POSTGRES_USER=flask
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flask_db
  database:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    ports:
      - 5432:5432 
    networks:
      - private
    environment:
      - POSTGRES_USER=flask
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flask_db
volumes:
  postgres_data:
networks:
  private:
    driver: bridge
